//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Extobj.rc
//


#define VERSION_NUM			"1.01"

#ifdef _DEBUG
#define VERSION_STR		"v" VERSION_NUM " DEBUG"
#else
#define VERSION_STR		"v" VERSION_NUM
#endif



#define M_DESC                          4
#define DB_ABOUT                        101
#define EXO_ABOUT                       102
#define EXO_BUTTON                      103
#define ID_ICONA                        104
#define DB_ADVSETUP                     106
#define IDST_OBJNAME                    128
#define IDST_AUTHOR                     129
#define IDST_COPYRIGHT                  130
#define IDST_COMMENT                    131
#define IDST_HTTP                       132
#define ID_HELP                         133
#define IDS_DEFNAME                     133
#define ID_EDITPATH                     134
#define ID_EDITBROWSE                   135
#define ID_EDITDRAW                     136
#define IDC_TRANS                       137
#define IDC_WRAP                        138
#define IDC_MIP_MAP                     139
#define IDC_MAIN_IMAGE                  140
#define IDC_WRAPV                       140
#define IDC_SECOND_IMAGE                141
#define IDC_MIP_MAP2                    141
#define IDC_HEIGHT_MAP                  142
#define IDC_MIP_MAP3                    142
#define IDC_MIP_MAPH                    142
#define IDC_MMTRANS                     143
#define IDC_FOG                         144
#define IDC_INTERPOLATE_H               144
#define IDC_INTERPOLATEH                144
#define IDC_INTERPOLATE                 145
#define IDC_LOCATE                      146
#define IDC_FOG2                        147
#define IDC_AUTO_REDRAW                 148
#define M_ACTION_SHOW                   401
#define M_ACTION_HIDE                   402
#define M_ACTION_TRANS_ON               403
#define M_ACTION_TRANS_OFF              404
#define M_ACTION_LOAD_IMAGE             405
#define M_ACTION_SET_WIDTH              406
#define M_ACTION_SET_HEIGHT             407
#define M_ACTION_SET_TILT               408
#define M_ACTION_SET_ANGLE              409
#define M_ACTION_SET_ROLL               410
#define M_ACTION_SET_XOFFSET            411
#define M_ACTION_SET_ELEVATION          412
#define M_ACTION_SET_YOFFSET            413
#define M_ACTION_SET_XCENTER            414
#define M_ACTION_SET_YCENTER            415
#define M_ACTION_SET_VANISH             416
#define M_ACTION_SET_ZOOM               417
#define M_ACTION_REDRAW                 418
#define M_ACTION_ADJUST_ANGLE           419
#define M_ACTION_ADJUST_XOFFSET         420
#define M_ACTION_ADJUST_YOFFSET         421
#define M_ACTION_ADJUST_ELEVATION       422
#define M_ACTION_WALK_FORWARD           423
#define M_ACTION_WALK_BACK              424
#define M_ACTION_WALK_LEFT              425
#define M_ACTION_WALK_RIGHT             426
#define M_ACTION_WRAPX_ON               427
#define M_ACTION_WRAPX_OFF              428
#define M_ACTION_WRAPY_ON               429
#define M_ACTION_WRAPY_OFF              430
#define M_EXP_GET_WIDTH                 431
#define M_EXP_GET_HEIGHT                432
#define M_EXP_GET_IMAGE_WIDTH           433
#define M_EXP_GET_IMAGE_HEIGHT          434
#define M_EXP_GET_FILE                  435
#define M_EXP_GET_TRANS                 436
#define M_EXP_GET_SHOW                  437
#define M_EXP_GET_TILT                  438
#define M_EXP_GET_ANGLE                 439
#define M_EXP_GET_ROLL                  440
#define M_EXP_GET_XOFFSET               441
#define M_EXP_GET_ELEVATION             442
#define M_EXP_GET_YOFFSET               443
#define M_EXP_GET_XCENTER               444
#define M_EXP_GET_YCENTER               445
#define M_EXP_GET_VANISH                446
#define M_EXP_GET_ZOOM                  447
#define M_EXP_GET_WRAPX                 448
#define M_EXP_GET_WRAPY                 449
#define M_EXP_GET_MAPX                  450
#define M_EXP_GET_MAPY                  451
#define M_EXP_GET_MAPXZ                 452
#define M_EXP_GET_MAPYZ                 453
#define M_EXP_GET_MAPWIDTH              454
#define M_EXP_GET_MAPHEIGHT             455
#define M_EXP_GET_MAPWIDTHZ             456
#define M_EXP_GET_MAPHEIGHTZ            457
#define M_EXP_GET_MAPANGLE              458
#define M_EXP_GET_MAPVISIBLE            459
#define M_ACTION_SET_RES                460
#define M_ACTION_SET_RESMODE            461
#define M_ACTION_SET_THICK              462
#define M_EXP_GET_RESX                  463
#define M_EXP_GET_RESY                  464
#define M_EXP_GET_RESMODE               465
#define M_EXP_GET_RESMODEPARAM          466
#define M_EXP_GET_THICK                 467
#define M_ACTION_ADJUST_TILT            468
#define M_ACTION_ADJUST_ROLL            469
#define M_ACTION_SET_XRES               470
#define M_ACTION_SET_YRES               471
#define M_ACTION_LOAD_IMAGENUM          472
#define M_ACTION_LOAD_IMAGENAME         473
#define M_ACTION_LOAD_IMAGE2            474
#define M_ACTION_LOAD_IMAGE2NUM         475
#define M_ACTION_LOAD_IMAGE2NAME        476
#define M_ACTION_LOAD_IMAGEH            477
#define M_ACTION_LOAD_IMAGEHNUM         478
#define M_ACTION_LOAD_IMAGEHNAME        479
#define M_EXP_GET_IMAGE_NUM             480
#define M_EXP_GET_IMAGE2_WIDTH          481
#define M_EXP_GET_IMAGE2_HEIGHT         482
#define M_EXP_GET_IMAGE2_NUM            483
#define M_EXP_GET_IMAGE2_FILE           484
#define M_EXP_GET_IMAGEH_WIDTH          485
#define M_EXP_GET_IMAGEH_HEIGHT         486
#define M_EXP_GET_IMAGEH_NUM            487
#define M_EXP_GET_IMAGEH_FILE           489
#define M_EXP_GET_IMAGE_HEIGHT_AT       490
#define M_ACTION_UNLOAD_IMAGE2          491
#define M_ACTION_UNLOAD_IMAGEH          492
#define M_ACTION_FOG_ON                 493
#define M_ACTION_FOG_OFF                494
#define M_ACTION_CHOOSEFOGCOLOR         495
#define M_ACTION_SETFOGCOLOR            496
#define M_ACTION_SETFOGRED              497
#define M_ACTION_SETFOGGREEN            498
#define M_ACTION_SETFOGBLUE             499
#define M_ACTION_SETFOGDISTANCE         500
#define M_EXP_GET_FOG                   501
#define M_EXP_GET_FOGRED                502
#define M_EXP_GET_FOGGREEN              503
#define M_EXP_GET_FOGBLUE               504
#define M_EXP_GET_FOGDISTANCE           505
#define M_ACTION_SET_XOFFSET2           506
#define M_ACTION_SET_YOFFSET2           507
#define M_ACTION_ADJUST_XOFFSET2        508
#define M_ACTION_ADJUST_YOFFSET2        509
#define M_ACTION_SET_ANGLE2             510
#define M_ACTION_ADJUST_ANGLE2          511
#define M_EXP_GET_XOFFSET2              512
#define M_EXP_GET_YOFFSET2              513
#define M_EXP_GET_ANGLE2                514
#define M_ACTION_SET_THICKNESSMODE      515
#define M_EXP_GET_THICKNESSMODE         516
#define M_ACTION_INTERPOL_ON            517
#define M_ACTION_INTERPOL_OFF           518
#define M_ACTION_HINTERPOL_ON           519
#define M_ACTION_HINTERPOL_OFF          520
#define M_EXP_GET_INTERPOL              521
#define M_EXP_GET_HINTERPOL             522
#define M_ACTION_MIPMAP_ON              523
#define M_ACTION_MIPMAP_OFF             524
#define M_ACTION_MIPMAP2_ON             525
#define M_ACTION_MIPMAP2_OFF            526
#define M_ACTION_MIPMAPH_ON             527
#define M_ACTION_MIPMAPH_OFF            528
#define M_EXP_GET_MIPMAP                529
#define M_EXP_GET_MIPMAP2               530
#define M_EXP_GET_MIPMAPH               531
#define M_ACTION_AUTOREDRAW_ON          532
#define M_ACTION_AUTOREDRAW_OFF         533
#define M_EXP_GET_AUTOREDRAW            534
#define M_ACTION_MIPMAP_TRANS           535
#define M_ACTION_MIPMAP_TRANS_OFF       536
#define M_EXP_GET_MAPVISIBLEZ           537
#define ID_WEBSITE                      1002
#define ID_ABOUT                        1003
#define ID_MODE7IMAGE                   1004
#define ID_IMAGEVIEW                    1006
#define IDC_IMAGENUM                    1008
#define IDC_PREVIMAGE                   1009
#define IDC_NEXTIMAGE                   1010
#define IDC_INSERTBEFORE                1011
#define IDC_INSERTAFTER                 1012
#define IDC_EDITIMAGENAME               1013
#define IDC_REMOVE                      1014
#define IDC_DRAWBOX                     1015
#define IDC_IMPORTIMAGE                 1015
#define IDC_SLIDER1                     1016
#define IDC_SLIDER                      1016
#define IDC_SLIDER2                     1017
#define IDC_OPTIONTABS                  1018
#define ID_ADVANCED                     1021
#define IDC_WRAPH                       1022
#define IDC_FOGCOLOR                    1023
#define IDC_EDIT1                       1024
#define IDC_FOGAMOUNT                   1024
#define IDC_MMCOLOR                     1025
#define IDC_MMCBOX                      1026
#define IDC_FOGCBOX                     1027
#define IDC_EDIT2                       1028
#define IDC_THICKNESS                   1028
#define IDC_EDIT3                       1029
#define IDC_RESX                        1029
#define IDC_EDIT4                       1030
#define IDC_RESY                        1030
#define IDC_RESMODE                     1031
#define IDC_EDIT5                       1032
#define IDC_RESPARAM                    1032
#define IDC_THICKMODE                   1033
#define MN_ACTIONS                      20000
#define MN_CONDITIONS                   20001
#define MN_EXPRESSIONS                  20002
#define DB_SETUP                        20003
#define M_ACT_COORDINATE                20200
#define M_ACT_ACOORDINATE               20201
#define M_ACT_PERCENT                   20202
#define M_ACT_DIMENSION                 20203
#define M_ACT_ANGLE                     20204
#define M_ACT_AANGLE                    20205
#define M_ACT_IMAGEFILE                 20206
#define M_ACT_OFFSET                    20207
#define M_ACT_DISTANCE                  20208
#define M_ACT_SX                        20209
#define M_ACT_SY                        20210
#define M_ACT_SZ                        20211
#define M_ACT_SWIDTH                    20212
#define M_ACT_SHEIGHT                   20213
#define M_ACT_SANGLE                    20214
#define M_ACT_RESX                      20215
#define M_ACT_RESY                      20216
#define M_ACT_RESMODE                   20217
#define M_ACT_RESMODE2                  20218
#define M_ACT_THICK                     20219
#define M_ACT_IMAGEID                   20220
#define M_ACT_IMAGENAME                 20221
#define M_ACT_FOGDISTANCE               20222
#define M_ACT_FOGCOLOR                  20223
#define M_ACT_RED                       20224
#define M_ACT_GREEN                     20225
#define M_ACT_BLUE                      20226
#define M_ACT_THICKNESSMODE             20227
#define M_ACT_MIPTRANSCOLOR             20228
#define IDMN_ACTION_SHOW                25000
#define IDMN_ACTION_HIDE                25001
#define IDMN_ACTION_TRANS_OFF           25002
#define IDMN_ACTION_TRANS_ON            25003
#define IDMN_ACTION_LOAD_IMAGE          25004
#define IDMN_ACTION_SET_WIDTH           25005
#define IDMN_ACTION_SET_HEIGHT          25006
#define IDMN_ACTION_SET_TILT            25007
#define IDMN_ACTION_SET_ANGLE           25008
#define IDMN_ACTION_SET_ROLL            25009
#define IDMN_ACTION_SET_XOFFSET         25010
#define IDMN_ACTION_SET_ELEVATION       25011
#define IDMN_ACTION_SET_YOFFSET         25012
#define IDMN_ACTION_SET_XCENTER         25013
#define IDMN_ACTION_SET_YCENTER         25014
#define IDMN_ACTION_SET_VANISH          25015
#define IDMN_ACTION_SET_ZOOM            25016
#define IDMN_ACTION_REDRAW              25017
#define IDMN_ACTION_ADJUST_ANGLE        25018
#define IDMN_ACTION_ADJUST_XOFFSET      25019
#define IDMN_ACTION_ADJUST_YOFFSET      25020
#define IDMN_ACTION_ADJUST_ELEVATION    25021
#define IDMN_ACTION_WALK_FORWARD        25022
#define IDMN_ACTION_WALK_BACK           25023
#define IDMN_ACTION_WALK_LEFT           25024
#define IDMN_ACTION_WALK_RIGHT          25025
#define IDMN_ACTION_WRAPX_ON            25026
#define IDMN_ACTION_WRAPX_OFF           25027
#define IDMN_ACTION_WRAPY_ON            25028
#define IDMN_ACTION_WRAPY_OFF           25029
#define IDMN_ACTION_SET_RES             25030
#define IDMN_ACTION_SET_RESMODE         25031
#define IDMN_ACTION_SET_THICK           25032
#define IDMN_ACTION_ADJUST_TILT         25033
#define IDMN_ACTION_ADJUST_ROLL         25034
#define IDMN_ACTION_SET_XRES            25035
#define IDMN_ACTION_SET_YRES            25036
#define IDMN_ACTION_LOAD_IMAGENUM       25037
#define IDMN_ACTION_LOAD_IMAGENAME      25038
#define IDMN_ACTION_LOAD_IMAGE2         25039
#define IDMN_ACTION_LOAD_IMAGE2NUM      25040
#define IDMN_ACTION_LOAD_IMAGE2NAME     25041
#define IDMN_ACTION_LOAD_IMAGEH         25042
#define IDMN_ACTION_LOAD_IMAGEHNUM      25043
#define IDMN_ACTION_LOAD_IMAGEHNAME     25044
#define IDMN_ACTION_UNLOAD_IMAGE2       25045
#define IDMN_ACTION_UNLOAD_IMAGEH       25046
#define IDMN_ACTION_FOG_ON              25047
#define IDMN_ACTION_FOG_OFF             25048
#define IDMN_ACTION_CHOOSEFOGCOLOR      25049
#define IDMN_ACTION_SETFOGCOLOR         25050
#define IDMN_ACTION_SETFOGRED           25051
#define IDMN_ACTION_SETFOGGREEN         25052
#define IDMN_ACTION_SETFOGBLUE          25053
#define IDMN_ACTION_SETFOGDISTANCE      25054
#define IDMN_ACTION_SET_THICKNESSMODE   25055
#define IDMN_ACTION_SET_XOFFSET2        25056
#define IDMN_ACTION_SET_YOFFSET2        25057
#define IDMN_ACTION_ADJUST_XOFFSET2     25058
#define IDMN_ACTION_ADJUST_YOFFSET2     25059
#define IDMN_ACTION_SET_ANGLE2          25060
#define IDMN_ACTION_ADJUST_ANGLE2       25061
#define IDMN_ACTION_INTERPOL_ON         25062
#define IDMN_ACTION_INTERPOL_OFF        25063
#define IDMN_ACTION_HINTERPOL_ON        25064
#define IDMN_ACTION_HINTERPOL_OFF       25065
#define IDMN_ACTION_MIPMAP_ON           25066
#define IDMN_ACTION_MIPMAP_OFF          25067
#define IDMN_ACTION_MIPMAP2_ON          25068
#define IDMN_ACTION_MIPMAP2_OFF         25069
#define IDMN_ACTION_MIPMAPH_ON          25070
#define IDMN_ACTION_MIPMAPH_OFF         25071
#define IDMN_ACTION_AUTOREDRAW_ON       25072
#define IDMN_ACTION_AUTOREDRAW_OFF      25073
#define IDMN_ACTION_MIPMAP_TRANS        25074
#define IDMN_ACTION_MIPMAP_TRANS_OFF    25075
#define IDMN_CONDITION                  26000
#define IDMN_EXP_GET_FILE               27000
#define IDMN_EXP_GET_WIDTH              27001
#define IDMN_EXP_GET_HEIGHT             27002
#define IDMN_EXP_GET_IMAGE_WIDTH        27003
#define IDMN_EXP_GET_IMAGE_HEIGHT       27004
#define IDMN_EXP_GET_TRANS              27005
#define IDMN_EXP_GET_SHOW               27006
#define IDMN_EXP_GET_TILT               27007
#define IDMN_EXP_GET_ANGLE              27008
#define IDMN_EXP_GET_ROLL               27009
#define IDMN_EXP_GET_XOFFSET            27010
#define IDMN_EXP_GET_ELEVATION          27011
#define IDMN_EXP_GET_YOFFSET            27012
#define IDMN_EXP_GET_XCENTER            27013
#define IDMN_EXP_GET_YCENTER            27014
#define IDMN_EXP_GET_VANISH             27015
#define IDMN_EXP_GET_ZOOM               27016
#define IDMN_EXP_GET_WRAPX              27017
#define IDMN_EXP_GET_WRAPY              27018
#define IDMN_EXP_GET_MAPX               27019
#define IDMN_EXP_GET_MAPY               27020
#define IDMN_EXP_GET_MAPXZ              27021
#define IDMN_EXP_GET_MAPYZ              27022
#define IDMN_EXP_GET_MAPWIDTH           27023
#define IDMN_EXP_GET_MAPHEIGHT          27024
#define IDMN_EXP_GET_MAPWIDTHZ          27025
#define IDMN_EXP_GET_MAPHEIGHTZ         27026
#define IDMN_EXP_GET_MAPANGLE           27027
#define IDMN_EXP_GET_MAPVISIBLE         27028
#define IDMN_EXP_GET_RESX               27029
#define IDMN_EXP_GET_RESY               27030
#define IDMN_EXP_GET_RESMODE            27031
#define IDMN_EXP_GET_RESMODEPARAM       27032
#define IDMN_EXP_GET_THICK              27033
#define IDMN_EXP_GET_IMAGE_NUM          27034
#define IDMN_EXP_GET_IMAGE2_WIDTH       27035
#define IDMN_EXP_GET_IMAGE2_HEIGHT      27036
#define IDMN_EXP_GET_IMAGE2_NUM         27037
#define IDMN_EXP_GET_IMAGE2_FILE        27038
#define IDMN_EXP_GET_IMAGEH_WIDTH       27039
#define IDMN_EXP_GET_IMAGEH_HEIGHT      27040
#define IDMN_EXP_GET_IMAGEH_NUM         27041
#define IDMN_EXP_GET_IMAGEH_FILE        27042
#define IDMN_EXP_GET_IMAGE_HEIGHT_AT    27043
#define IDMN_EXP_GET_FOG                27044
#define IDMN_EXP_GET_FOGRED             27045
#define IDMN_EXP_GET_FOGGREEN           27046
#define IDMN_EXP_GET_FOGBLUE            27047
#define IDMN_EXP_GET_FOGDISTANCE        27048
#define IDMN_EXP_GET_XOFFSET2           27049
#define IDMN_EXP_GET_YOFFSET2           27050
#define IDMN_EXP_GET_ANGLE2             27051
#define IDMN_EXP_GET_THICKNESSMODE      27052
#define IDMN_EXP_GET_INTERPOL           27053
#define IDMN_EXP_GET_HINTERPOL          27054
#define IDMN_EXP_GET_MIPMAP             27055
#define IDMN_EXP_GET_MIPMAP2            27056
#define IDMN_EXP_GET_MIPMAPH            27057
#define IDMN_EXP_GET_AUTOREDRAW         27058
#define IDMN_EXP_GET_MAPVISIBLEZ        27059
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        108
#define _APS_NEXT_COMMAND_VALUE         40039
#define _APS_NEXT_CONTROL_VALUE         1032
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
